worker_processes 1;
error_log /dev/stderr info;
pid /tmp/nginx.pid;

events { worker_connections 256; }

http {
    access_log /dev/stdout;
    server {
        listen 8080;
        location / {
            default_type text/plain;
            content_by_lua_block { ngx.say("hello from openresty") }
        }
    }
}
